### ISSUE TITLE
deobf jar

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [Jebacka/luigigihack#1]
[LuigiHack-final-uwu.zip](https://github.com/Jebacka/luigigihack/files/9551906/LuigiHack-final-uwu.zip)

here's the fully deobf jar lol, poop obf moment

**Comment by therealbush** [comment]
😵🚬

**Comment by Jebacka** [comment]
I didn't even use the hack, but thanks for the info

**Comment by Tarkan-Zarrouk** [comment]
They're using that superblaubeere obf thing, it's shit and the same dude who created that obf has a deobf that deobf his own obf kek
